api/urls.py
from django.urls import path, include
from rest_framework.routers import DefaultRouter
from drf_spectacular.views import SpectacularAPIView, SpectacularSwaggerView

from . import views

app_name = 'api'


router = DefaultRouter(use_regex_path=False)
router.register('users', views.UserViewSet, basename='user')
router.register('workspace', views.WorkspaceViewSet, basename='workspace')
router.register('workspace/<int:ws_pk>/comment',
                views.WorkspaceCommentViewSet,
                basename='workspace-comment')
router.register('workspace/<int:ws_pk>/tag',
                views.TagViewSet,
                basename='tag')
router.register('workspace/<int:ws_pk>/priority',
                views.PriorityViewSet,
                basename='priority')
router.register('workspace/<int:ws_pk>/status',
                views.StatusViewSet,
                basename='status')
router.register('workspace/<int:ws_pk>/category',
                views.CategoryViewSet,
                basename='category')
router.register('workspace/<int:ws_pk>/category/<int:cat_pk>/comment',
                views.CategoryCommentViewSet,
                basename='category-comment')
router.register('workspace/<int:ws_pk>/category/<int:cat_pk>/project',
                views.ProjectViewSet,
                basename='project')
router.register('workspace/<int:ws_pk>/category/<int:cat_pk>/project/<int:pr_pk>/comment',
                views.ProjectCommentViewSet,
                basename='project-comment')
router.register('workspace/<int:ws_pk>/category/<int:cat_pk>/project/<int:pr_pk>/task',
                views.ProjectTaskViewSet,
                basename='project-task')
router.register('workspace/<int:ws_pk>/category/<int:cat_pk>/task',
                views.TaskViewSet,
                basename='task')
router.register('workspace/<int:ws_pk>/category/<int:cat_pk>/task/<int:task_pk>/comment',
                views.TaskCommentViewSet,
                basename='task-comment')

urlpatterns = [
    path('', include(router.urls)),
    path('schema/', SpectacularAPIView.as_view(), name='schema'),
    path('docs/', SpectacularSwaggerView.as_view(url_name='api:schema'),
         name='docs'),
]

demo/urls.py
from django.urls import path, include

from demo import views

app_name = "demo"

urlpatterns = [
    path('', views.home, name='home'),

    path('workspace/add/', views.WorkspaceCreateView.as_view(),
         name='workspace-create'),
    path('workspace/<int:pk>/manage/',
         views.workspace_manage, name='workspace-manage'),
    path('workspace/<int:pk>/detail/',
         views.workspace_detail, name='workspace-detail'),
    path('workspace/<int:pk>/update/',
         views.WorkspaceUpdateView.as_view(), name='workspace-update'),
    path('workspace/<int:pk>/delete/',
         views.WorkspaceDeleteView.as_view(), name='workspace-delete'),

    path('workspace/comment/<int:pk>/update/',
         views.WorkspaceCommentUpdateView.as_view(), name='workspace-comment-update'),
    path('workspace/comment/<int:pk>/delete/',
         views.WorkspaceCommentDeleteView.as_view(), name='workspace-comment-delete'),

    path('category/add/',
         views.CategoryCreateView.as_view(),
         name='category-create'),
    path('category/<int:cat_pk>/detail/',
         views.category_detail,
         name='category-detail'),
    path('category/<int:pk>/update/',
         views.CategoryUpdateView.as_view(),
         name='category-update'),
    path('category/<int:pk>/delete/',
         views.CategoryDeleteView.as_view(),
         name='category-delete'),

    path('category/comment/<int:pk>/update/',
         views.CategoryCommentUpdateView.as_view(),
         name='category-comment-update'),
    path('workspace/comment/<int:pk>/delete/',
         views.CategoryCommentDeleteView.as_view(),
         name='category-comment-delete'),

    path('tag/add/', views.TagCreateView.as_view(),
         name='tag-create'),
    path('tag/<int:pk>/update/',
         views.TagUpdateView.as_view(), name='tag-update'),
    path('tag/<int:pk>/delete/',
         views.TagDeleteView.as_view(), name='tag-delete'),

    path('priority/add/', views.PriorityCreateView.as_view(),
         name='priority-create'),
    path('priority/<int:pk>/update/',
         views.PriorityUpdateView.as_view(), name='priority-update'),
    path('priority/<int:pk>/delete/',
         views.PriorityDeleteView.as_view(), name='priority-delete'),

    path('status/add/', views.StatusCreateView.as_view(),
         name='status-create'),
    path('status/<int:pk>/update/',
         views.StatusUpdateView.as_view(), name='status-update'),
    path('status/<int:pk>/delete/',
         views.StatusDeleteView.as_view(), name='status-delete'),

    path('task/add/', views.TaskCreateView.as_view(), name='task-create'),
    path('task/<slug:uuid>/detail/', views.task_detail_view, name='task-detail'),
    path('task/<slug:uuid>/delete/',
         views.TaskDeleteView.as_view(), name='task-delete'),

    path('task/comment/<int:pk>/update/',
         views.TaskCommentUpdateView.as_view(), name='task-comment-update'),
    path('task/comment/<int:pk>/delete/',
         views.TaskCommentDeleteView.as_view(), name='task-comment-delete'),

    path('project/add/', views.ProjectCreateView.as_view(), name='project-create'),
    path('project/<slug:uuid>/detail/',
         views.project_detail_view, name='project-detail'),
    path('project/<slug:uuid>/delete/',
         views.ProjectDeleteView.as_view(), name='project-delete'),

    path('project/comment/<int:pk>/update/',
         views.ProjectCommentUpdateView.as_view(), name='project-comment-update'),
    path('project/comment/<int:pk>/delete/',
         views.ProjectCommentDeleteView.as_view(), name='project-comment-delete'),

    path('archive/', views.archive_view, name='archive'),

    path('signup/', views.SignUpView.as_view(), name='signup'),
]

demo/forms/project.py
from django import forms as djf
from django.db.models import Q

from core import models as core_models
from demo import utils as demo_utils

class ProjectForm(demo_utils.CustomModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        if self.instance.pk:
            self.fields["workspace"].queryset = core_models.Workspace\
                .objects.filter(pk=self.instance.workspace.pk)
            self.fields["status"].queryset = core_models.Status.objects.filter(
                workspace=self.instance.workspace)
            self.fields["priority"].queryset = core_models.Priority.objects.filter(
                workspace=self.instance.workspace)
            self.fields["tags"].queryset = core_models.Tag.objects.filter(
                workspace=self.instance.workspace)
            self.fields["parent"].queryset = core_models.Project.objects.filter(
                Q(workspace=self.instance.workspace)
                & Q(category=self.instance.category)
                & ~Q(pk=self.instance.pk)
            )
    class Meta:
        model = core_models.Project
        widgets = {
            "estimated_start_date": djf.DateInput(attrs={'type': 'date'}),
            "estimated_end_date": djf.DateInput(attrs={'type': 'date'}),
            "actual_start_date": djf.DateInput(attrs={'type': 'date'}),
            "actual_end_date": djf.DateInput(attrs={'type': 'date'}),
        }
        fields = [
            "title",
            "detail",
            "workspace",
            "category",
            "tags",
            "status",
            "priority",
            "parent",
            "is_visible",
            "estimated_start_date",
            "estimated_end_date",
            "actual_start_date",
            "actual_end_date",
            "estimated_effort",
            "actual_effort"
        ]


class ProjectCommentForm(demo_utils.CustomModelForm):
    class Meta:
        model = core_models.ProjectComment
        fields = ["content", "project", "parent"]

demo/views.py
from django.core.checks import messages
from django.core.exceptions import PermissionDenied
from django.forms import ValidationError
from django.http.response import HttpResponseRedirect
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import edit as djev
from django.contrib.auth.forms import UserCreationForm
from django.urls import reverse_lazy
from django.db.models import Q

from core import models as core_models
from demo import utils as demo_utils
from demo import forms as demo_forms


class SignUpView(djev.CreateView):
    form_class = UserCreationForm
    success_url = reverse_lazy("login")
    template_name = "registration/signup.html"


class WorkspaceCreateView(LoginRequiredMixin, djev.CreateView):
    model = core_models.Workspace
    fields = ["name", "is_default",]
    template_name = "demo/generic/create.html"

    def get_success_url(self):
        return reverse_lazy("demo:workspace-detail", kwargs={"pk": self.object.pk})

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        demo_utils.update_context_main(self.request, context)
        return context

    def form_valid(self, form):
        if not form.instance.pk:
            form.instance.created_by = self.request.user
        form.instance.updated_by = self.request.user
        cnd = self.model.objects.filter(
            Q(name__iexact=form.instance.name)
            & Q(created_by=self.request.user)
        )
        if cnd:
            msg = "Name(lowercased) should be unique for a user."
            form.add_error("name", ValidationError(
                message=msg, code='invalid'))
            return super().form_invalid(form)
        return super().form_valid(form)


class WorkspaceUpdateView(LoginRequiredMixin, djev.UpdateView):
    model = core_models.Workspace
    fields = ["name", "is_default",]
    template_name = "demo/generic/update.html"

    def get(self, request, *args, **kwargs):
        if request.user != self.get_object().created_by:
            raise PermissionDenied("You are not the creator of this object.")
        return super().get(request, *args, **kwargs)

    def get_success_url(self):
        return reverse_lazy("demo:workspace-detail", kwargs={"pk": self.object.pk})

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        demo_utils.update_context_main(self.request, context)
        return context

    def form_valid(self, form):
        form.instance.updated_by = self.request.user
        cnd = self.model.objects.filter(
            Q(name__iexact=form.instance.name)
            & Q(created_by=self.request.user)
            & ~Q(pk=self.object.pk)
        )
        if cnd:
            msg = "Name(lowercased) should be unique for a user."
            form.add_error("name", ValidationError(
                message=msg, code='invalid'))
            return super().form_invalid(form)
        return super().form_valid(form)


class WorkspaceDeleteView(LoginRequiredMixin, djev.DeleteView):
    model = core_models.Workspace
    success_url = reverse_lazy("demo:home")
    template_name = "demo/generic/delete.html"

    def get(self, request, *args, **kwargs):
        if request.user != self.get_object().created_by:
            raise PermissionDenied("You are not the creator of this object.")
        return super().get(request, *args, **kwargs)

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        demo_utils.update_context_main(self.request, context)
        return context


class CategoryCreateView(LoginRequiredMixin, demo_utils.CustomWsCreateView):
    model = core_models.Category
    template_name = "demo/generic/create.html"
    fields = ["name", "description", "workspace", "parent"]

    def get_success_url(self):
        return reverse_lazy("demo:workspace-manage", kwargs={"pk": self.object.workspace.pk})

    def form_valid(self, form):
        cnd = self.model.objects.filter(
            Q(name__iexact=form.instance.name)
            & Q(workspace=form.instance.workspace)
            & Q(parent=form.instance.parent)
        )
        if cnd:
            msg = "Name(lowercased)-workspace-parent should be unique."
            form.add_error("name",
                           ValidationError(message=msg, code='invalid'))
            return super().form_invalid(form)
        return super().form_valid(form)


class CategoryUpdateView(LoginRequiredMixin, demo_utils.CustomWsUpdateView):
    model = core_models.Category
    template_name = "demo/generic/update.html"
    fields = ["name", "description", "workspace", "parent"]

    def get_success_url(self):
        return reverse_lazy("demo:workspace-manage", kwargs={"pk": self.object.workspace.pk})

    def form_valid(self, form):
        cnd = self.model.objects.filter(
            Q(name__iexact=form.instance.name)
            & Q(workspace=form.instance.workspace)
            & ~Q(pk=self.object.pk)
        )
        if cnd:
            msg = "Name(lowercased)-workspace-parent should be unique."
            form.add_error("name", ValidationError(
                message=msg, code='invalid'))
            return super().form_invalid(form)
        return super().form_valid(form)


class CategoryDeleteView(LoginRequiredMixin, demo_utils.CustomWsDeleteView):
    model = core_models.Category
    template_name = "demo/generic/delete.html"

    def get_success_url(self):
        return reverse_lazy("demo:workspace-manage", kwargs={"pk": self.object.workspace.pk})


class TagCreateView(LoginRequiredMixin, demo_utils.CustomWsCreateView):
    model = core_models.Tag
    template_name = "demo/generic/create.html"
    fields = ["name", "workspace"]

    def get_success_url(self):
        return reverse_lazy("demo:workspace-manage", kwargs={"pk": self.object.workspace.pk})

    def form_valid(self, form):
        cnd = self.model.objects.filter(
            Q(name__iexact=form.instance.name)
            & Q(workspace=form.instance.workspace)
        )
        if cnd:
            msg = "Name(lowercased)-workspace should be unique."
            form.add_error("name", ValidationError(
                message=msg, code='invalid'))
            return super().form_invalid(form)
        return super().form_valid(form)


class TagUpdateView(LoginRequiredMixin, demo_utils.CustomWsUpdateView):
    model = core_models.Tag
    template_name = "demo/generic/update.html"
    fields = ["name", "workspace"]

    def get_success_url(self):
        return reverse_lazy("demo:workspace-manage", kwargs={"pk": self.object.workspace.pk})

    def form_valid(self, form):
        cnd = self.model.objects.filter(
            Q(name__iexact=form.instance.name)
            & Q(workspace=form.instance.workspace)
            & ~Q(pk=self.object.pk)
        )
        if cnd:
            msg = "Name(lowercased)-workspace should be unique."
            form.add_error("name", ValidationError(
                message=msg, code='invalid'))
            return super().form_invalid(form)
        return super().form_valid(form)


class TagDeleteView(LoginRequiredMixin, demo_utils.CustomWsDeleteView):
    model = core_models.Tag
    template_name = "demo/generic/delete.html"

    def get_success_url(self):
        return reverse_lazy("demo:workspace-manage", kwargs={"pk": self.object.workspace.pk})


class PriorityCreateView(LoginRequiredMixin, demo_utils.CustomWsCreateView):
    model = core_models.Priority
    template_name = "demo/generic/create.html"
    fields = ["name", "order", "description", "workspace"]

    def get_success_url(self):
        return reverse_lazy("demo:workspace-manage", kwargs={"pk": self.object.workspace.pk})

    def form_valid(self, form):
        cnd = self.model.objects.filter(
            Q(name__iexact=form.instance.name)
            & Q(workspace=form.instance.workspace)
        )
        if cnd:
            msg = "Name(lowercased)-workspace should be unique."
            form.add_error("name", ValidationError(
                message=msg, code='invalid'))
            return super().form_invalid(form)
        return super().form_valid(form)


class PriorityUpdateView(LoginRequiredMixin, demo_utils.CustomWsUpdateView):
    model = core_models.Priority
    template_name = "demo/generic/update.html"
    fields = ["name", "order", "description", "workspace"]

    def get_success_url(self):
        return reverse_lazy("demo:workspace-manage", kwargs={"pk": self.object.workspace.pk})

    def form_valid(self, form):
        form.instance.updated_by = self.request.user
        cnd = self.model.objects.filter(
            Q(name__iexact=form.instance.name)
            & Q(workspace=form.instance.workspace)
            & ~Q(pk=self.object.pk)
        )
        if cnd:
            msg = "Name(lowercased)-workspace should be unique."
            form.add_error("name", ValidationError(
                message=msg, code='invalid'))
            return super().form_invalid(form)
        return super().form_valid(form)


class PriorityDeleteView(LoginRequiredMixin, demo_utils.CustomWsDeleteView):
    model = core_models.Priority
    template_name = "demo/generic/delete.html"

    def get_success_url(self):
        return reverse_lazy("demo:workspace-manage", kwargs={"pk": self.object.workspace.pk})


class StatusCreateView(LoginRequiredMixin, demo_utils.CustomWsCreateView):
    model = core_models.Status
    template_name = "demo/generic/create.html"
    fields = ["name", "order", "description", "workspace"]

    def get_success_url(self):
        return reverse_lazy("demo:workspace-manage", kwargs={"pk": self.object.workspace.pk})

    def form_valid(self, form):
        cnd = self.model.objects.filter(
            Q(name__iexact=form.instance.name)

demo/templates/demo/category.html
{% extends "demo/base.html" %}
{% load static %}
{% load crispy_forms_tags %}

{% block main-content %}

<h4>
  Workspace: <a href="{{ workspace.get_absolute_url }}"
    class="text-warning-emphasis bg-warning-subtle"
    >{{ workspace.name | title }}</a>
  > Category: <a href="{{ category.get_absolute_url }}"
    class="text-danger-emphasis bg-danger-subtle"
    >{{ category.name | title }}</a>
</h4>
<div class="my-2">
  <p class="">{{ category.detail }}</p>
  <p class="">
    <span class="">Owner: {{ category.created_by }}</span>
    <span class="">| Created at: {{ category.created_at }}</span>
    <span class="">| Updated at: {{ category.updated_at }}</span>
  </p>
</div>
<hr>

<div class="d-inline-block">
  <h3>Projects</h3>
</div>
<div class="d-inline-block float-end">
  <a href="{% url 'demo:project-create' %}?ws_pk={{ workspace.pk }}&cat_pk={{ category.pk }}"
    class="btn text-primary-emphasis bg-primary-subtle me-2"
    >Create Project</a>
</div>
<hr>
{% if category_projects %}
<table class="table table-striped">
  <thead>
    <tr>
      <th scope="col">Title</th>
      <th scope="col">Parent</th>
      <th scope="col">Priority</th>
      <th scope="col">Status</th>
      <th scope="col">End(est)</th>
      <th scope="col">Start</th>
      <th scope="col">End</th>
      <th scope="col">Edit</th>
      <th scope="col">Delete</th>
    </tr>
  </thead>
  <tbody>
    {% for project in category_projects %}
    <tr>
      <td><a href="{{ project.get_absolute_url }}"
          class="link-dark"
          >{{ project.title }}</a></td>
      <td><a href="{{ project.parent.get_absolute_url }}"
          class="link-dark"
          >{{ project.parent.title|default_if_none:"" }}</a></td>
      <td>{{ project.priority }}</td>
      <td>{{ project.status }}</td>
      <td>{{ project.estimated_end_date|default_if_none:"" }}</td>
      <td>{{ project.actual_start_date|default_if_none:"" }}</td>
      <td>{{ project.actual_end_date|default_if_none:"" }}</td>
      <td>
        <a href="{% url 'demo:project-detail' project.uuid %}">
          <i class="bi-pencil-square fs-5 text-primary-emphasis"></i>
        </a>
      </td>
      <td>
        <a href="{% url 'demo:project-delete' project.uuid %}">
          <i class="bi-trash3 fs-5 text-danger-emphasis"></i>
        </a>
      </td>
    </tr>
    {% endfor %}
  </tbody>
</table>
{% else %}
<p>There are no visible projects in this category. Check archive if needed.</p>
{% endif %}
<hr>
<div class="d-inline-block">
  <h3>Tasks</h3>
</div>
<div class="d-inline-block float-end">
  <a href="{% url 'demo:task-create' %}?ws_pk={{ workspace.pk }}&cat_pk={{ category.pk }}"
    class="btn text-primary-emphasis bg-primary-subtle me-2"
    >Create Task</a>
</div>
<hr>

<h4>Project Tasks</h4>
{% if category_project_tasks %}
<table class="table table-striped">
  <thead>
    <tr>
      <th scope="col">Project</th>
      <th scope="col">Title</th>
      <th scope="col">Parent</th>
      <th scope="col">Priority</th>
      <th scope="col">Status</th>
      <th scope="col">End(est)</th>
      <th scope="col">Start</th>
      <th scope="col">End</th>
      <th scope="col">Edit</th>
      <th scope="col">Delete</th>
    </tr>
  </thead>
  <tbody>
    {% for task in category_project_tasks %}
    <tr>
      <td><a href="{{ task.project.get_absolute_url }}"
          class="link-dark"
          >{{ task.project.title }}</a></td>
      <td><a href="{{ task.get_absolute_url }}"
          class="link-dark"
          >{{ task.title }}</a></td>
      <td><a href="{{ task.parent.get_absolute_url }}"
          class="link-dark"
          >{{ task.parent.title }}</a></td>
      <td>{{ task.priority }}</td>
      <td>{{ task.status }}</td>
      <td>{{ task.estimated_end_date|default_if_none:"" }}</td>
      <td>{{ task.actual_start_date|default_if_none:"" }}</td>
      <td>{{ task.actual_end_date|default_if_none:"" }}</td>
      <td>
        <a href="{% url 'demo:task-detail' task.uuid %}">
          <i class="bi-pencil-square fs-5 text-primary-emphasis"></i>
        </a>
      </td>
      <td>
        <a href="{% url 'demo:task-delete' task.uuid %}">
          <i class="bi-trash3 fs-5 text-danger-emphasis"></i>
        </a>
      </td>
    </tr>
    {% endfor %}
  </tbody>
</table>
{% else %}
<p>There are no visible tasks related to projects. Check archive if needed.</p>
{% endif %}
<hr>

<h4>Independent Tasks</h4>
{% if category_independent_tasks %}
<table class="table table-striped">
  <thead>
    <tr>
      <th scope="col">Title</th>
      <th scope="col">Parent</th>
      <th scope="col">Priority</th>
      <th scope="col">Status</th>
      <th scope="col">End(est)</th>
      <th scope="col">Start</th>
      <th scope="col">End</th>
      <th scope="col">Edit</th>
      <th scope="col">Delete</th>
    </tr>
  </thead>
  <tbody>
    {% for task in category_independent_tasks %}
    <tr>
      <td><a href="{{ task.get_absolute_url }}"
          class="link-dark"
          >{{ task.title }}</a></td>
      <td><a href="{{ task.parent.get_absolute_url }}"
          class="link-dark"
          >{{ task.parent.title }}</a></td>
      <td>{{ task.priority }}</td>
      <td>{{ task.status }}</td>
      <td>{{ task.estimated_end_date|default_if_none:"" }}</td>
      <td>{{ task.actual_start_date|default_if_none:"" }}</td>
      <td>{{ task.actual_end_date|default_if_none:"" }}</td>
      <td>
        <a href="{% url 'demo:task-detail' task.uuid %}">
          <i class="bi-pencil-square fs-5 text-primary-emphasis"></i>
        </a>
      </td>
      <td>
        <a href="{% url 'demo:task-delete' task.uuid %}">
          <i class="bi-trash3 fs-5 text-danger-emphasis"></i>
        </a>
      </td>
    </tr>
    {% endfor %}
  </tbody>
</table>
{% else %}
<p>There are no visible independent tasks. Check archive if needed.</p>
{% endif %}
<hr>

<div class="mb-3">
  <h4>Existing Comments</h4>
  {% if rendered_comments %}
  {{ rendered_comments | safe }}
  {% else %}
  <p>There are no comments yet.</p>
  {% endif %}
</div>

<div class="mb-3">
  <h4>Comment</h4>
  <div class="border rounded border-secondary p-4">
    <form method="post">
      {% csrf_token %}
      {{ comment_form|crispy }}
      <input type="submit" value="Post Comment"
        class="btn btn text-success-emphasis bg-success-subtle">
    </form>
  </div>
</div>

{% endblock main-content %}

demo/templates/demo/index.html
{% extends "demo/base.html" %}

{% block main-content %}

{% if user.is_authenticated %}

<div class="my-2">
  <h3 class="d-inline-block">Workspace List</h3>
  <div class="d-inline-block float-end">
    <a href="{% url 'demo:workspace-create' %}"
      class="btn text-secondary-emphasis bg-secondary-subtle">Create Workspace</a>
  </div>
  <hr>
  {% for ws in workspaces %}
  <div class="my-2">
    <h4 class="d-inline-block">{{ ws.name|title }} </h4>
    <div class="float-end">
      <a href="{{ ws.get_absolute_url }}"
        class="btn text-primary-emphasis bg-primary-subtle">View</a>
      <a href="{% url 'demo:workspace-manage' ws.pk %}" 
        class="btn text-success-emphasis bg-success-subtle">Manage</a>
      <a href="{% url 'demo:workspace-update' ws.pk %}" 
        class="btn text-warning-emphasis bg-warning-subtle">Update</a>
      <a href="{% url 'demo:workspace-delete' ws.pk %}" 
        class="btn text-danger-emphasis bg-danger-subtle">Delete</a>
    </div>
  </div>
  <hr>
  {% endfor %}
</div>

{% endif %}

{% endblock main-content %}